### ISSUE TITLE
Type checking with Flow

### ISSUE THREAD

**Issue by kyleshevlin** [kyleshevlin/shevyjs#1]

**Comment by frytyler** [comment]
Hey @kyleshevlin I noticed you have a branch started for this issue are you working on that still or would you like me to grab this as well?

**Comment by kyleshevlin** [comment]
If you would like to take a shot at it, you are welcome to do so. I haven't touched that branch in quite some time. I'd probably start from scratch myself if took on this issue.

Before you do, though, I'm not sure what will be gained by adding Flow to such a small library. We have unit tests in place, and I think that might be more than solid enough for the scale of this project. Do you have any thoughts regarding that?

**Comment by frytyler** [comment]
Ya taking a look at the utils which would be the main area where flow would be used there's maybe some small benefits however it's very readable and as you said 100% tested. I would say you are probably right may not be the best time. 

The only other thing to consider is that it is a dev dependency so the cost is low if it helps in the future. But really provides no benefit to a develop using ShevyJS.

All that to say I vote not now for this.

**Comment by kyleshevlin** [comment]
Sounds good. I'm going to close the issue. Thanks for your contributions! I'll get a release out soon. 👍
