### ISSUE TITLE
Add array of fontScale presets

### ISSUE THREAD

**Issue by kyleshevlin** [kyleshevlin/shevyjs#2]
Shevy does not intend to solve anyone's font size decisions, but that doesn't mean we can't make some presets to let devs have some good options to start with.

**Comment by frytyler** [comment]
Hey @kyleshevlin I can hit this for you, I noticed you already provide a set of `defaultOptions` [here](https://github.com/kyleshevlin/shevyjs/blob/master/src/constants/index.js#L4) so is this intended to provided a set of fontScale's like multiple options to choose from. Is there an example from the `scss` repo?

**Comment by kyleshevlin** [comment]
I was considering creating some default typography scales based on tools like the following:

http://type-scale.com/
http://www.modularscale.com/

Instead of an array, it could be an object with keys that represent scales like 'major-third', 'augmented-fourth', etc, where the value is a font-scale array.

Then, the user can either pass an array or a string to font-scale and Shevy would respond accordingly. We probably want to throw an error if the key doesn't exist.

Those are my thoughts on how I was going to solve it.
