### ISSUE TITLE
Add demo

### ISSUE THREAD

**Issue by stereobooster** [kyleshevlin/shevyjs#4]
Add demo like this http://nowodzinski.pl/syncope/ or http://kyleamathews.github.io/typography.js/

**Comment by kyleshevlin** [comment]
Given that is a WYSIWYG tool, I think that makes sense for them. I'm not sure it makes sense for me to make such a thing, nor do I really have the time right now. I could create a Github page where I ported/updated the stuff from the Sass version's Github page: http://kyleshevlin.github.io/shevy/examples. Is the important thing the interactivity, or the ability to see examples?

**Comment by stereobooster** [comment]
Interactivity is important bit, because with CSS-in-JS you get this for free. 

> nor do I really have the time right now

Not saying you should do it. Leave it as open issue (if you like the idea), maybe somebody will drop a PR for it.

**Comment by ha404** [comment]
Do you happen to know when to use `base-spacing` vs `line-height-spacing`? The official Shevy docs don't really explain the usage well.

**Comment by kyleshevlin** [comment]
The docs explain the difference. `base-spacing` respects the `proximity` option, whereas `line-height-spacing` ignores it. These are convenience methods to be used however you would like. Personally, I always use `base-spacing`, but wanted to give people both options. Please file a new issue if you feel the docs are unclear on a topic.
