### ISSUE TITLE
dev dependency?

### ISSUE THREAD

**Issue by ha404** [kyleshevlin/shevyjs#5]
Why is this package recommended to be installed as a dev dependency?

**Comment by kyleshevlin** [comment]
I default to saving everything in devDependencies unless I know for certain otherwise, so the simple answer is I could be wrong. If you'd like to make a PR to adjust the docs, that would be great.

**Comment by ha404** [comment]
https://github.com/kyleshevlin/shevyjs/pull/6 👍
