### ISSUE TITLE
instantiating globally

### ISSUE THREAD

**Issue by ha404** [kyleshevlin/shevyjs#7]
Hi there! I was wondering if this was a good approach to instantiating and using this globally?

Instantiate:
```javascript
import root from 'window-or-global'
import Shevy from 'shevyjs'

export default root.shevy = root.shevy || new Shevy()
```

Use:
```javascript
import shevy from 'path/to/shevy'

const { content } = shevy
```

**Comment by kyleshevlin** [comment]
This is more a general JavaScript question than one particular to this library. Feel free to instantiate Shevy however you see fit. 👍
